Add file and line
ViaQ/logerr pull request #15
Opened 2020-12-17 11:50 UTC by eranra

2020-12-17 14:33 UTC, alanconway requested changes
Useful for devs, but logs are user facing and source locations make no sense to users. Suggest making this optional, enable with env var LOG_DEV=1. (If we add other optional developer-only features in future we can enable them with the same env var.) A couple of other suggestions, but good idea!

2020-12-17 14:33 UTC, alanconway commented on log/logger.go
> +	FileKey      = "file"
Use a single FileLineKey with the format "file:line" - less clutter in the log message and better chance that editors will be able to recognize as a source location.

2020-12-17 14:33 UTC, alanconway commented on log/logger.go
> +	file = filepath.Base(filepath.Dir(file)) + "/" + filepath.Base(file)
Suggest computing the path like this:
```
func sourcePath(file string) string {
	if wd, err := os.Getwd(); err == nil {
		if rel, err := filepath.Rel(wd, file); err == nil && !strings.HasPrefix(rel, "../") {
			return rel
		}
	}
	return filepath.Join(filepath.Base(filepath.Dir(file)), filepath.Base(file))
}

```
That way, if your working directory is inside the source tree, you'll get a valid relative path that an editor can follow. If you're outside, fall back to your format.

2020-12-17 14:33 UTC, alanconway commented on log/observer_test.go
> +	if !ok {
Make FileLineKey optional, not an error if missing.

2020-12-20 17:45 UTC, eranra commented
Moving and fixing all of those in PR #16 https://github.com/ViaQ/logerr/pull/16

2020-12-20 17:52 UTC, eranra commented
Closing this PR moving all to #16

2020-12-20 17:52 UTC, closed without merging